config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :customers do
    resources :loans do
      member do
        get :installment_schedule
      end
    end
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
# frozen_string_literal: true

class Loan < ApplicationRecord
  ANNUAL_INEREST_RATE = 0.20
  belongs_to :customer

  validates :number_of_installments, inclusion: { in: 1..6 }

  validates :number_of_installments, :amount, presence: true

  before_create :add_loan_interest

  def total_amount
    (amount + interest)
  end

  def installment_schedule
    monthly_amount = monthly_installment_amount
    start_date = created_at
    installments = []
    (1..number_of_installments).each do |num|
      installment_date = start_date + (num - 1).months
      installment_amount = monthly_amount
      installments << { date: installment_date, amount: installment_amount }
    end
    installments
  end

  private

  def add_loan_interest
    interest_rate = (number_of_installments / 12.0) * ANNUAL_INEREST_RATE
    self.interest = amount * interest_rate
  end

  def monthly_installment_amount
    total_amount / number_of_installments
  end
end

app/controllers/loans_controller.rb
# frozen_string_literal: true

# loans controller
class LoansController < ApplicationController
  before_action :set_customer
  before_action :set_loan, only: %i[show edit update destroy installment_schedule]

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show; end

  # GET /loans/new
  def new
    @loan = @customer.loans.build
  end

  # GET /loans/1/edit
  def edit; end

  # POST /loans or /loans.json
  def create
    @loan = @customer.loans.build(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to customer_loan_path(@customer, @loan), notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to customer_loan_path(@customer, @loan), notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to customer_loans_path(@customer), notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def installment_schedule
    @installment_schedule = @loan.installment_schedule
    @installment_schedule
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end

  def set_loan
    @loan = @customer.loans.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def loan_params
    params.require(:loan).permit(:amount, :number_of_installments, :duration).merge(customer_id: @customer.id)
  end
end

app/helpers/loans_helper.rb
# frozen_string_literal: true

# LoansHelper
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for [@customer, @loan] do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label 'number_of_installments (monthly)' %>
    <%= form.select :number_of_installments, (1..6) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', customer_loan_path(@customer,@loan) %> |
<%= link_to 'Back', customer_loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Number of installments (in months)</th>
      <th>Interest</th>
      <th>Total Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.amount %></td>
        <td><%= loan.number_of_installments %></td>
        <td><%= loan.interest %></td>
        <td><%= loan.total_amount %></td>
        <td><%= link_to 'Show', customer_loan_path(@customer,loan) %></td>
        <td><%= link_to 'Edit', edit_customer_loan_path(@customer,loan) %></td>
        <td><%= link_to 'Installment Schedule', installment_schedule_customer_loan_path(@customer,loan) %></td>
        <td><%= link_to 'Destroy', customer_loan_path(@customer,loan), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_customer_loan_path(@customer) %>

app/views/loans/installment_schedule.html.erb
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @installment_schedule.each do |installment| %>
      <tr>
        <td><%= installment[:date].strftime('%d/%m/%Y') %></td>
        <td><%= number_to_currency(installment[:amount]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', customer_loans_path(@customer) %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', customer_loans_path(@customer) %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @loan.amount %>
</p>

<p>
  <strong>Number of installments:</strong>
  <%= @loan.number_of_installments %>
</p>


<p>
  <strong>Interest:</strong>
  <%= @loan.interest %>
</p>

<p>
  <strong>Total Amount:</strong>
  <%= @loan.total_amount %>
</p>

<%= link_to 'Edit', edit_customer_loan_path(@loan) %> |
<%= link_to 'Back', customer_loans_path(@customer) %>